# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  coveralls: ergeon/coveralls-orb@1.0.9
jobs:
  run_tests:
    parallelism: 2
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install --upgrade pip setuptools wheel
            PIP=venv/bin/pip make install
      - run:
          name: Test
          command: |
            source venv/bin/activate
            
            TEST_FILES=$(circleci tests glob "tests/test_*.py" | circleci tests split --total=$CIRCLE_NODE_TOTAL)
          
            mkdir -p coverage
            coverage run -m pytest $TEST_FILES

      - store_artifacts:
          path: coverage

      - deploy:
          name: Deploy
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts \
              | grep -o 'https://[^"]*' \
              | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" -P coverage --input-file -
            
            source venv/bin/activate
            FOLDER_NAME="coverage" make coverage-combine
            make coverage-report
            
            if [ -n "$CIRCLE_PULL_REQUEST" ] || [ "${CIRCLE_BRANCH}" = "develop" ] || [ "${CIRCLE_BRANCH}" = "master" ]; then
              coveralls
            else
              for I in 1 2 3 4 5
              do
                PULL_REQUEST_NUMBER=$(curl -sb -H "Accept: application/json" -H "Authorization: Token $GITHUB_API_TOKEN" "https://api.github.com/repos/ergeon/$CIRCLE_PROJECT_REPONAME/commits/$CIRCLE_SHA1/pulls" | python -c 'import json,sys;data=json.load(sys.stdin);print(data[0]["number"]) if data and isinstance(data, list) else print()')

                if [ -n "$PULL_REQUEST_NUMBER" ]; then
                  CI_PULL_REQUEST=$PULL_REQUEST_NUMBER coveralls
                  break
                else
                  if [[ $I == 5 ]]; then
                    echo "Pull Request wasn't found for this commit."
                    echo "Please re-run this build once Pull Request will be opened."
                    exit 1
                  fi
                  echo "PR not found yet, trying again after a while."
                  echo "Waiting for 60 seconds..."
                  sleep 60
                fi
              done
            fi

workflows:
  deploy_and_notify:
    jobs:
      - run_tests:
          context:
            - "DEFAULT ERGEON"
            - github-secrets
