# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  coveralls: ergeon/coveralls-orb@1.0.9
jobs:
  run_tests:
    parallelism: 3
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            venv/bin/pip install --upgrade pip setuptools wheel
            PIP=venv/bin/pip make install
      - run:
          name: Test
          command: |
            source venv/bin/activate
            
            TESTFILES=$(circleci tests glob "tests/test_*.py" | \
            circleci tests split --split-by=timings --timings-type=classname --total=$CIRCLE_NODE_TOTAL)
          
            mkdir -p coverage
            coverage run -m pytest $TESTFILES

      - persist_to_workspace:
          root: coverage
          paths:
            - .coverage*

      - deploy:
          name: Deploy
          command: |
            ls -la coverage

workflows:
  deploy_and_notify:
    jobs:
      - run_tests:
          context:
            - "DEFAULT ERGEON"
            - github-secrets
